export const products = [
  {
    id: 1,
    name: "Wireless Earbuds Pro",
    description: "High-quality wireless earbuds with active noise cancellation and 24-hour battery life.",
    price: 129.99,
    image: "/placeholder.svg?height=400&width=400&text=Wireless+Earbuds",
    isNew: true,
  },
  {
    id: 2,
    name: "SmartWatch X",
    description:
      "Track your fitness, receive notifications, and more with this advanced smartwatch with heart rate monitoring.",
    price: 199.99,
    image: "/placeholder.svg?height=400&width=400&text=SmartWatch",
    discount: 15,
  },
  {
    id: 3,
    name: "Portable Bluetooth Speaker",
    description: "Waterproof portable speaker with amazing sound quality and 20-hour battery life.",
    price: 79.99,
    image: "/placeholder.svg?height=400&width=400&text=Bluetooth+Speaker",
  },
  {
    id: 4,
    name: "UltraBook Pro",
    description: "Powerful laptop with the latest processor, 16GB RAM, and 512GB SSD for professional use.",
    price: 1299.99,
    image: "/placeholder.svg?height=400&width=400&text=UltraBook+Pro",
    isNew: true,
    discount: 10,
  },
  {
    id: 5,
    name: "4K HDR Monitor",
    description: "Ultra-sharp 27-inch 4K monitor with HDR support for professionals and gamers.",
    price: 349.99,
    image: "/placeholder.svg?height=400&width=400&text=4K+Monitor",
  },
  {
    id: 6,
    name: "RGB Mechanical Keyboard",
    description: "RGB mechanical keyboard with customizable keys and tactile feedback for gaming enthusiasts.",
    price: 129.99,
    image: "/placeholder.svg?height=400&width=400&text=Mechanical+Keyboard",
    discount: 20,
  },
  {
    id: 7,
    name: "Ergonomic Wireless Mouse",
    description: "Ergonomic wireless mouse with adjustable DPI and long battery life for comfortable use.",
    price: 49.99,
    image: "/placeholder.svg?height=400&width=400&text=Wireless+Mouse",
  },
  {
    id: 8,
    name: "Gaming Headset Pro",
    description: "Immersive gaming headset with surround sound and noise-cancelling microphone for competitive gaming.",
    price: 89.99,
    image: "/placeholder.svg?height=400&width=400&text=Gaming+Headset",
    isNew: true,
  },
]
